require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - '*.gemspec'

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/metabase/error.rb

Metrics/MethodLength:
  Max: 20
