AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/metabase/error.rb

Metrics/MethodLength:
  Max: 20
