language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3

before_install:
  - gem install bundler -v 1.16.2

script:
  - bundle exec rubocop
  - bundle exec rake spec

cache: bundler

branches:
  only:
    - master

notifications:
  email: false
